affordable/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("cinema.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinema/urls.py
from django.urls import path
from cinema import views as cinema_views

app_name = "cinema"

urlpatterns = [
    path("search/", cinema_views.MovieCatalogView.as_view(), name="search"),
    path("", cinema_views.MovieCatalogView.as_view(), name="catalog"),
    path("movie/<slug:movie_slug>/", cinema_views.MovieDetailView.as_view(), name="movie"),
    path("comment/<slug:movie_slug>/", cinema_views.AddComment.as_view(), name="movie_comment"),
    path("review/<slug:movie_slug>/", cinema_views.AddReview.as_view(), name="movie_review"),
    path("movie/<slug:movie_slug>/tickets/", cinema_views.TicketView.as_view(), name="movie_tickets"),
    path("movie/<slug:movie_slug>/reserve/", cinema_views.ReservationView.as_view(), name="movie_reserve"),
]

main/urls.py
from django.urls import path
from main import views as main_views

app_name = "main"

urlpatterns = [
    path("", main_views.MovieView.as_view(), name="index"),
    path("about/", main_views.MovieAboutView.as_view(), name="about"),
    path("contacts/", main_views.MovieContactsView.as_view(), name="contacts"),
    path("privacy/", main_views.MoviePrivacyView.as_view(), name="privacy"),
    path("help-center/", main_views.MovieFaqView.as_view(), name="faq"),
]

cinema/models.py
from django.db import models



cinema/forms.py
from typing import Literal
from django import forms

from main.models import Comments, Movie, Reviews, Seat

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields: tuple[Literal['text']] = ('text',)

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ('title', 'text', 'rating',)


class SeatSelectionForm(forms.Form):
    movie = forms.ModelChoiceField(queryset=Movie.objects.all(), label="Фільм")
    seats = forms.ModelMultipleChoiceField(
        queryset=Seat.objects.filter(status="free"),
        widget=forms.CheckboxSelectMultiple,
        label="Місця",
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if "movie" in self.fields:
            self.fields["seats"].queryset = Seat.objects.filter(
                movie_session=self.fields["movie"].queryset.first(), status="free"
            )

    def clean(self):
        cleaned_data = super().clean()
        movie = cleaned_data.get("movie")
        seats = cleaned_data.get("seats")

        if movie and seats:
            for seat in seats:
                if seat.movie_session != movie or seat.status != "free":
                    raise forms.ValidationError(
                        "Обрані місця недоступні для цього фільму або вже зайняті."
                    )

        return cleaned_data

cinema/views.py
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import get_list_or_404, redirect, render, get_object_or_404
from cinema.utils import q_search
from main.models import Category, Comments, Genre, Movie, MovieShots, Seat
from django.views.generic.base import View
from cinema.forms import CommentForm, ReviewForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .utils import q_search

class MovieCatalogView(View):
    def get(self, request):
        genres = Genre.objects.all()
        categories = Category.objects.all()
        movies = Movie.objects.all()

        genre_slug = request.GET.get('genre')
        category_slug = request.GET.get('category')
        query = request.GET.get('q')

        if category_slug:
            movies = Movie.objects.filter(category__slug=category_slug)
            movies = get_list_or_404(movies)
        elif query:
            movies = q_search(query)

        if genre_slug:
            movies = movies.filter(genres__slug=genre_slug)

        paginator = Paginator(movies, 1)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'movies': page_obj,
            'genres': genres,
            'categories': categories,
            'genre_slug': genre_slug,
        }
        return render(request, 'cinema/catalog.html', context)

class MovieDetailView(View):
    def get(self, request, movie_slug):
        movie = get_object_or_404(Movie, slug=movie_slug)
        movies = Movie.objects.exclude(slug=movie_slug)
        comments = movie.comments.all()
        reviews = movie.reviews.all()
        review_form = ReviewForm()
        movieshots = MovieShots.objects.filter(movie=movie)
        context = {
            "movie": movie,
            "movies": movies,
            "comments": comments,
            "reviews": reviews,
            "review_form": review_form,
            "movieshots": movieshots,
        }
        return render(request, "cinema/movie.html", context)

class AddComment(LoginRequiredMixin, View):
    def post(self, request, movie_slug):
        form = CommentForm(request.POST)
        movie = get_object_or_404(Movie, slug=movie_slug)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.movie = movie
            comment.user = request.user
            comment.save()
        return redirect("cinema:movie", movie_slug=movie_slug)

class AddReview(LoginRequiredMixin, View):
    def post(self, request, movie_slug):
        form = ReviewForm(request.POST)
        movie = get_object_or_404(Movie, slug=movie_slug)
        if form.is_valid():
            review = form.save(commit=False)
            review.movie = movie
            review.user = request.user 
            review.save()
        return redirect("cinema:movie", movie_slug=movie_slug)


class TicketView(LoginRequiredMixin, View):
    def get(self, request, movie_slug):
        movie = get_object_or_404(Movie, slug=movie_slug)
        seats = movie.seat.all()
        context = {
            "movie": movie,
            "seats": seats,
        }
        return render(request, "cinema/tickets.html", context)


class ReservationView(LoginRequiredMixin, View):
    def post(self, request, movie_slug):
        selected_seat_ids = request.POST.getlist("seat_ids[]")
        session_id = request.POST.get("session_id")

        movie = get_object_or_404(Movie, slug=movie_slug)
        selected_seats = Seat.objects.filter(id__in=selected_seat_ids)

        # Mark selected seats as reserved
        for seat in selected_seats:
            seat.status = "reserved"
            seat.save()

        # Perform any additional logic (e.g., create a payment record, send notifications, etc.)

        return redirect("cinema:movie_tickets", movie_slug=movie.slug)

cinema/templates/cinema/cart.html
{% extends 'main/base.html' %}

{% block content %}
  <h1>Кошик</h1>
  <h2>Обрані місця для фільму: {{ movie.title }}</h2>
  <ul>
    {% for seat in selected_seats %}
      <li>Місце номер {{ seat.seat_no }}</li>
    {% endfor %}
  </ul>
  <p>Загальна сума: {{ total_price }} грн.</p>
{% endblock %}

cinema/templates/cinema/catalog.html
{% extends "main/base.html" %}
{% load static %}
{% load cinema_tags %}

{% block content %}
    <section class="section section--first section--bg" data-bg="{% static "main/img/bg/section__bg.jpg" %}">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section__wrap">
                        <h1 class="section__title section__title--head">Каталог</h1>
                        <ul class="breadcrumbs">
                            <li class="breadcrumbs__item"><a href="{% url "main:index" %}">Головна</a></li>
                            <li class="breadcrumbs__item breadcrumbs__item--active">Каталог</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="filter">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="filter__content">
                        <form method="get" action="{% if request.GET.q %}{% url "cinema:search" %}{% else %}{% url 'cinema:catalog' %}{% endif %}" class="filter__content">
                            <div class="filter__items">
                                {% if request.GET.q %}
                                <input type="hidden" name="q" value="{{ request.GET.q }}">
                                {% endif %}
                                <select class="filter__select" name="genre">
                                    <option value="">Всі жанри</option>
                                    {% for genre in genres %}
                                        <option value="{{ genre.slug }}" {% if genre.slug == genre_slug %}selected{% endif %}>{{ genre.name }}</option>
                                    {% endfor %}
                                </select>
                                <select class="filter__select" name="category">
                                    <option value="">Всі категорії</option>
                                    {% for category in categories %}
                                        <option value="{{ category.slug }}" {% if category.slug == category_slug %}selected{% endif %}>{{ category.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <button class="filter__btn" type="submit"><span>Застосувати</span></button>
                        </form>
                        <span class="filter__amount">Показано {{ movies|length }} з {{ movies.paginator.count }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="section section--catalog">
        <div class="container">
            <div class="row">
            {% for movie in movies %}
                <div class="col-6 col-sm-4 col-lg-3 col-xl-2">
                    <div class="item">
                        <a href="{% url 'catalog:movie' movie.slug %}" class="item__cover">
                            {% if movie.img %}
                                <img src="{{ movie.img.url }}" alt="">
                            {% else %}
                                <img src="{% static 'main/img/notfound.svg' %}" alt="Not found img">
                            {% endif %}
                            <span class="item__play">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                    <path d="M18.54,9,8.88,3.46a3.42,3.42,0,0,0-5.13,3V17.58A3.42,3.42,0,0,0,7.17,21a3.43,3.43,0,0,0,1.71-.46L18.54,15a3.42,3.42,0,0,0,0-5.92Zm-1,4.19L7.88,18.81a1.44,1.44,0,0,1-1.42,0,1.42,1.42,0,0,1-.71-1.23V6.42a1.42,1.42,0,0,1,.71-1.23A1.51,1.51,0,0,1,7.17,5a1.54,1.54,0,0,1,.71.19l9.66,5.58a1.42,1.42,0,0,1,0,2.46Z" />
                                </svg>
                            </span>
                        </a>
                        <div class="item__content">
                            <h3 class="item__title"><a href="{% url 'catalog:movie' movie.slug %}">{% autoescape off %}{% if movie.headline %}{{ movie.headline }}{% else %}{{ movie.title }}{% endif %}{% endautoescape %}</a></h3>
                            <span class="item__category">
                                {% for genre in movie.genre.all %}
                                    <a href="#">{{ genre.name }}</a>{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </span>
                            <span class="item__rate">{{ movie.get_average_rating}}</span>
                        </div>
                    </div>
                </div>
            {% endfor %} 
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="section__paginator">
                        <span class="section__paginator-pages">Показано {{ movies|length }} з {{ movies.paginator.count }}</span>
                        <ul class="section__paginator-list">
                            <li>
                                <a href="{% if movies.has_previous %}?page={{ movies.previous_page_number }}{% endif %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                        <path
                                            d="M17,11H9.41l3.3-3.29a1,1,0,1,0-1.42-1.42l-5,5a1,1,0,0,0-.21.33,1,1,0,0,0,0,.76,1,1,0,0,0,.21.33l5,5a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42L9.41,13H17a1,1,0,0,0,0-2Z" />
                                    </svg>
                                    <span>Попередня</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% if movies.has_next %}?page={{ movies.next_page_number }}{% endif %}">
                                    <span>Наступна</span>
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                        <path
                                            d="M17.92,11.62a1,1,0,0,0-.21-.33l-5-5a1,1,0,0,0-1.42,1.42L14.59,11H7a1,1,0,0,0,0,2h7.59l-3.3,3.29a1,1,0,0,0,0,1.42,1,1,0,0,0,1.42,0l5-5a1,1,0,0,0,.21-.33A1,1,0,0,0,17.92,11.62Z" />
                                    </svg>
                                </a>
                            </li>
                        </ul>
                        <ul class="paginator">
                            <li class="paginator__item paginator__item--prev">
                                <a href="{% if movies.has_previous %}?{% change_params page=movies.previous_page_number %}{% else %}#{% endif %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" viewBox="0 0 24 24">
                                        <path d="M8.5,12.8l5.7,5.6c0.4,0.4,1,0.4,1.4,0c0,0,0,0,0,0c0.4-0.4,0.4-1,0-1.4l-4.9-5l4.9-5c0.4-0.4,0.4-1,0-1.4c-0.2-0.2-0.4-0.3-0.7-0.3c-0.3,0-0.5,0.1-0.7,0.3l-5.7,5.6C8.1,11.7,8.1,12.3,8.5,12.8C8.5,12.7,8.5,12.7,8.5,12.8z" />
                                    </svg>
                                </a>
                            </li>
                            {% for page in movies.paginator.page_range %}
                                {% if page >= movies.number|add:-2 and page <= movies.number|add:2 %}
                                    {% if page == movies.number %}
                                        <li class="paginator__item paginator__item--active">
                                            <a href="?{% change_params page=page %}">{{ page }}</a>
                                        </li>
                                    {% else %}
                                        <li class="paginator__item">
                                            <a href="?{% change_params page=page %}">{{ page }}</a>
                                        </li>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                            <li class="paginator__item paginator__item--next">
                                <a href="{% if movies.has_next %}?{% change_params page=movies.next_page_number %}{% else %}#{% endif %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                        <path d="M15.54,11.29,9.88,5.64a1,1,0,0,0-1.42,0,1,1,0,0,0,0,1.41l4.95,5L8.46,17a1,1,0,0,0,0,1.41,1,1,0,0,0,.71.3,1,1,0,0,0,.71-.3l5.66-5.65A1,1,0,0,0,15.54,11.29Z" />
                                    </svg>
                                </a>
                            </li>
                        </ul>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

cinema/templates/cinema/email_template.html
Hello {{first_name | title}},

Thank yo for purcahsing seat number {{seat_no}} for the movie {{movie_title}}.

Hope you enjoy it.

Thank you once again.
OtchereDev
(CEO DjangoMovies)

cinema/templates/cinema/movie.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
	<section class="section section--details">
		<div class="section__details-bg" data-bg="{{ movie.poster.url }}"></div>
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h1 class="section__title section__title--head">{{ movie.title }}</h1>
				</div>
				<div class="col-12 col-xl-6">
					<div class="item item--details">
						<div class="item__cover">
							<img src="{{ movie.img.url }}" alt="{{ movie.title }}">
						</div>
						<div class="item__content">
							<div class="item__wrap">
								<span class="item__rate">{{ movie.get_average_rating}}</span>
								<ul class="item__list">
									<li>{{ movie.age }} +</li>
								</ul>
							</div>
							<ul class="item__meta">
								<li><span>Жанр:</span> {% for genre in movie.genre.all %}<a href="#">{{ genre.name }}</a>{% endfor %}</li>
								<li><span>Тривалість:</span> {{ movie.runtime }} хв</li>
								<li><span>Країна:</span> <a href="#">{{ movie.country }}</a></li>
								<li><span>Прем'єра:</span> {{ movie.world_premiere }}</li>
							</ul>
							<ul class="item__meta item__meta--second">
								<li><span>Режисер:</span> {% for director in movie.directors.all %}<a href="actor.html">{{ director.name }}</a>{% endfor %}</li>
								<li><span>Актори:</span> {% for actor in movie.directors.all %}<a href="actor.html">{{ actor.name }}</a>{% endfor %}</li>
							</ul>
						</div>

						<div class="item__description item__description--details">
							<p>{{ movie.description }}</p>
						</div>
					</div>
				</div>
				<div class="col-12 col-xl-6">
					<video class="item item--details plyr"  controls crossorigin playsinline poster="{{ movie.poster.url }}" id="player">
						<source src="{{ movie.video.url }}" type="video/mp4" size="576">
						<source src="{{ movie.video.url }}" type="video/mp4" size="720">
						<source src="{{ movie.video.url }}" type="video/mp4" size="1080">
					</video>
				</div>
				<div class="hero__actions">
                    <a href="{% url 'cinema:movie_tickets' movie.slug %}" class="hero__btn">
                        <span>Купити квиток</span>
                    </a>
                </div>				
			</div>
		</div>
	</section>
	<section class="content">
		<div class="content__head">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<h2 class="content__title"></h2>
						<ul class="nav nav-tabs content__tabs" id="content__tabs" role="tablist">
							<li class="nav-item" role="presentation">
								<button id="1-tab" class="active" data-bs-toggle="tab" data-bs-target="#tab-1" type="button" role="tab" aria-controls="tab-1" aria-selected="true">Коментарі</button>
							</li>

							<li class="nav-item" role="presentation">
								<button id="2-tab" data-bs-toggle="tab" data-bs-target="#tab-2" type="button" role="tab" aria-controls="tab-2" aria-selected="false">Відгуки</button>
							</li>

							<li class="nav-item" role="presentation">
								<button id="3-tab" data-bs-toggle="tab" data-bs-target="#tab-3" type="button" role="tab" aria-controls="tab-3" aria-selected="false">Фото</button>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-12 col-lg-8">
					<div class="tab-content">
						<div class="tab-pane fade show active" id="tab-1" role="tabpanel" aria-labelledby="1-tab" tabindex="0">
							<div class="row">
								<div class="col-12">
									<div class="comments">
										<ul class="comments__list">
											{% for comment in comments %}
											<li class="comments__item">
												<div class="comments__autor">
													<img class="comments__avatar" src="{% static "main/img/bg/user.svg" %}" alt="">
													<span class="comments__name">{{ comment.user.username }}</span>
													<span class="comments__time">{{ comment.created_at }}</span>
												</div>
												<p class="comments__text">{{ comment.text }}</p>
											</li>
											{% endfor %}
										</ul>
										<form action="{% url 'cinema:movie_comment' movie.slug %}" method="post" class="sign__form sign__form--comments" id="formReview">
											{% csrf_token %}
											<input type="hidden" name="parent_comment_id" value="{{ parent_comment_id }}">
											<div class="sign__group">
												<textarea id="text" name="text" class="sign__textarea" placeholder="Введіть коментар"></textarea>
											</div>
											<button type="submit" class="sign__btn sign__btn--small"><span>Відправити</span></button>
										</form>
									</div>
								</div>
							</div>
						</div>
						<div class="tab-pane fade" id="tab-2" role="tabpanel" aria-labelledby="2-tab" tabindex="0">
							<div class="row">
								<div class="col-12">
									<div class="reviews">
										<ul class="reviews__list">
											{% for review in reviews %}
											<li class="reviews__item">
												<div class="reviews__autor">
													<img class="reviews__avatar" src="{% static "main/img/bg/user.svg" %}" alt="">
													<span class="reviews__name">{{ review.title }}</span>
													<span class="reviews__time">{{ review.created_at }}</span>

													<span class="reviews__rating"><svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" viewBox="0 0 24 24"><path d="M22,10.1c0.1-0.5-0.3-1.1-0.8-1.1l-5.7-0.8L12.9,3c-0.1-0.2-0.2-0.3-0.4-0.4C12,2.3,11.4,2.5,11.1,3L8.6,8.2L2.9,9C2.6,9,2.4,9.1,2.3,9.3c-0.4,0.4-0.4,1,0,1.4l4.1,4l-1,5.7c0,0.2,0,0.4,0.1,0.6c0.3,0.5,0.9,0.7,1.4,0.4l5.1-2.7l5.1,2.7c0.1,0.1,0.3,0.1,0.5,0.1v0c0.1,0,0.1,0,0.2,0c0.5-0.1,0.9-0.6,0.8-1.2l-1-5.7l4.1-4C21.9,10.5,22,10.3,22,10.1z"></path></svg>{{ review.rating }}</span>
												</div>
												<p class="reviews__text">{{ review.text }}</p>
											</li>
											{% endfor %}
										</ul>
										<form action="{% url "cinema:movie_review" movie.slug %}" method="post" class="sign__form sign__form--comments">
											{% csrf_token %}
											<div class="row">
												<div class="col-12 col-md-6">
													<div class="sign__group">
														<input type="text" name="title" class="sign__input" placeholder="Title">
													</div>
												</div>
												<div class="col-12 col-md-6">
													<div class="sign__group">
														<select class="sign__select" name="rating" id="rating">
															<option value="0">Рейтинг</option>
															<option value="1">1 зірка</option>
															<option value="2">2 зірки</option>
															<option value="3">3 зірки</option>
															<option value="4">4 зірки</option>
															<option value="5">5 зірок</option>
															<option value="6">6 зірок</option>
															<option value="7">7 зірок</option>
															<option value="8">8 зірок</option>
															<option value="9">9 зірок</option>
															<option value="10">10 зірок</option>
														</select>
													</div>
												</div>
												<div class="col-12">
													<div class="sign__group">
														<textarea name="text" class="sign__textarea" placeholder="Напишіть відгук"></textarea>
													</div>
												</div>

												<div class="col-12">
													<button type="submit" class="sign__btn sign__btn--small"><span>Відправити</span></button>
												</div>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
						<div class="tab-pane fade" id="tab-3" role="tabpanel" aria-labelledby="3-tab" tabindex="0">
							<div class="gallery" itemscope>
								<div class="row row--grid">
									{% for shot in movieshots %}
									<figure class="col-12 col-sm-6 col-xl-4" itemprop="associatedMedia" itemscope>
										<a href="img/gallery/project-1.jpg" itemprop="contentUrl" data-size="1920x1280">
											<img src="{{ shot.image.url }}" itemprop="thumbnail" alt="Image description" />
										</a>
										<figcaption itemprop="caption description">image of {{ movie.title }}</figcaption>
									</figure>
									{% endfor %}
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-12 col-lg-4">
					<div class="row">
						<div class="col-12">
							<h2 class="section__title section__title--sidebar">Вам також можуть сподобатись</h2>
						</div>
						{% for movie in movies %}
                        <div class="col-6 col-sm-4 col-lg-6">
							<div class="item">
								<a href="{% url "cinema:movie" movie.slug %}" class="item__cover">
									<img src="{{ movie.img.url }}" alt="">
									<span class="item__play">
										<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M18.54,9,8.88,3.46a3.42,3.42,0,0,0-5.13,3V17.58A3.42,3.42,0,0,0,7.17,21a3.43,3.43,0,0,0,1.71-.46L18.54,15a3.42,3.42,0,0,0,0-5.92Zm-1,4.19L7.88,18.81a1.44,1.44,0,0,1-1.42,0,1.42,1.42,0,0,1-.71-1.23V6.42a1.42,1.42,0,0,1,.71-1.23A1.51,1.51,0,0,1,7.17,5a1.54,1.54,0,0,1,.71.19l9.66,5.58a1.42,1.42,0,0,1,0,2.46Z"/></svg>
									</span>
								</a>
								<div class="item__content">
									<h3 class="item__title"><a href="{% url "cinema:movie" movie.slug %}">{{ movie.title }}</a></h3>
									<span class="item__category">
										{% for genre in movie.genre.all %}<a href="#">{{ genre.name }}</a>{% endfor %}
									</span>
									<span class="item__rate">{{ movie.rating }}</span>
								</div>
							</div>
						</div>
                        {% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock content %}

cinema/templates/cinema/tickets.html
{% load static %}

<!DOCTYPE html>
<html lang="uk">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'main/css/ticket.css' %}">
  <title>Бронювання місць у кінотеатрі</title>
</head>
<body>
  <div class="movie-container">
    <label for="session">Виберіть дату та час для {{ movie.title }}:</label>
    <select id="session">
      {% for seat in seats %}
        <option value="{{ seat.id }}" {% if forloop.first %}selected{% endif %}>З {{ seat.date_start }} до {{ seat.date_end }} ({{ movie.price }} грн)</option>
      {% endfor %}
    </select>
  </div>
  <ul class="showcase">
    <li>
      <div class="seat"></div>
      <small>Вільне</small>
    </li>
    <li>
      <div class="seat selected"></div>
      <small>Вибране</small>
    </li>
    <li>
      <div class="seat sold"></div>
      <small>Зайняте</small>
    </li>
  </ul>

  <div class="container">
    <div class="screen"></div>
        <div class="row">
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
        </div>
        <div class="row">
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
        </div>
        <div class="row">
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
        </div>
        <div class="row">
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
        </div>
        <div class="row">
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
        </div>
        <div class="row">
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
            <div class="seat"></div>
        </div>
  </div>

  <p class="text">
    Ви вибрали <span id="count">0</span> місць на суму <span id="total">0.00</span> грн.
  </p>
  
  <form action="{% url 'cinema:movie_reserve' movie.slug %}" method="post">
      {% csrf_token %}
      <label for="session">Виберіть сеанс:</label>
      <select name="session_id" id="session">
          {% for seat in seats %}
          <option value="{{ seat.id }}">{{ seat.start_time }} - {{ seat.end_time }} ({{ movie.price }} грн)</option>
          {% endfor %}
      </select>

      <h2>Виберіть місця:</h2>
      <div class="container">
          {% for seat in seats %}
          <div class="row">
              <input type="checkbox" id="seat{{ seat.id }}" name="seat_ids[]" value="{{ seat.id }}">
              <label for="seat{{ seat.id }}">Місце {{ seat.seat_number }}</label>
          </div>
          {% endfor %}
      </div>

      <button type="submit">Забронювати</button>
  </form>

  <script src="{% static 'main/js/backend.js' %}"></script>
</body>
</html>