affordable/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("cinema.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinema/urls.py
from django.urls import path
from cinema import views as cinema_views

app_name = "cinema"

urlpatterns = [
    path("search/", cinema_views.MovieCatalogView.as_view(), name="search"),
    path("", cinema_views.MovieCatalogView.as_view(), name="catalog"),
    path("movie/<slug:movie_slug>/", cinema_views.MovieDetailView.as_view(), name="movie"),
    path("comment/<slug:movie_slug>/", cinema_views.AddComment.as_view(), name="movie_comment"),
    path("review/<slug:movie_slug>/", cinema_views.AddReview.as_view(), name="movie_review"),
    path("movie/<slug:movie_slug>/tickets/", cinema_views.TicketView.as_view(), name="movie_tickets"),
    path("movie/<slug:movie_slug>/reserve/", cinema_views.ReservationView.as_view(), name="movie_reserve"),
]

main/urls.py
from django.urls import path
from main import views as main_views

app_name = "main"

urlpatterns = [
    path("", main_views.MovieView.as_view(), name="index"),
    path("about/", main_views.MovieAboutView.as_view(), name="about"),
    path("contacts/", main_views.MovieContactsView.as_view(), name="contacts"),
    path("privacy/", main_views.MoviePrivacyView.as_view(), name="privacy"),
    path("help-center/", main_views.MovieFaqView.as_view(), name="faq"),
]

users/urls.py
from django.urls import path
from users import views as user_views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

app_name = "users"

urlpatterns = [
    path("signin/", user_views.UserSigninView.as_view(), name="signin"),
    path("signup/", user_views.UserSignupView.as_view(), name="signup"),
    path("forgot/", user_views.UserForgotView.as_view(), name="forgot"),
    path("profile/", user_views.UserProfileView.as_view(), name="profile"),
    path("password-reset/", PasswordResetView.as_view(template_name='users/password_reset_form.html'), name="password_reset"),
    path("password-reset/done/", PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name="password_reset_done"),
    path('password-reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path("reset/done/", PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name="password_reset_complete"),
    path("logout/", user_views.UserSignoutView.as_view(), name="logout"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from main.models import Seat
from django.db.models.signals import post_save
from django.dispatch import receiver

class User(AbstractUser):
    image = models.ImageField(upload_to="users_image", blank=True, null=True, verbose_name="Аватарка:")
    booked_seats = models.ManyToManyField(Seat, blank=True)

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='custom_user_set',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        verbose_name='groups',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='custom_user_set',
        blank=True,
        help_text='Specific permissions for this user.',
        verbose_name='user permissions',
    )

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User

class UserSigninForm(AuthenticationForm):
    username = forms.CharField(max_length=150, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)
    
    class Meta:
        model = User
        fields = ['username', 'password']

class UserSignupForm(UserCreationForm):
    username = forms.CharField(max_length=150, required=True)
    email = forms.EmailField(max_length=254, required=True)
    password1 = forms.CharField(widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(widget=forms.PasswordInput, required=True)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name']

    def clean_password2(self) -> str:
        data = self.cleaned_data
        if data['password1'] != data['password2']: 
            raise forms.ValidationError("Паролі не співпадають")
        return data['password1']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такий email вже існує")
        return email

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("image", "first_name", "last_name", "username", "email")

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

users/views.py
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic.base import View
from django.shortcuts import redirect, render
from django.contrib import auth
from users.forms import UserSigninForm, UserSignupForm
from django.contrib.auth.views import LoginView

class UserSigninView(LoginView):
    form_class = UserSigninForm
    template_name = "users/signin.html"
    extra_context = {
        'title': 'Вхід'
    }

    def get_success_url(self) -> str:
        return reverse_lazy('users:profile')

class UserSignupView(View):
    def post(self, request):
        form = UserSignupForm(data=request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            return HttpResponseRedirect(reverse("users:profile"))
        
        context = {
            "form": form
        }
        return render(request, "users/signup.html", context)

    def get(self, request):
        form = UserSignupForm()
        context = {
            "form": form
        }
        return render(request, "users/signup.html", context)

class UserForgotView(View):
    def get(self, request):
        return render(request, "users/forgot.html")

class UserSignoutView(View):
    def post(self, request):
        auth.logout(request)
        return redirect(reverse("main:index"))

class UserProfileView(View):
    def get(self, request):
        return render(request, "users/profile.html")

users/templates/users/password_reset_complete.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <title>Password Reset Complete</title>
</head>
<body>
    <div class="container">
        <h2>Password Reset Complete</h2>
        <p>Your password has been set. You can now <a href="{% url 'users:signin' %}">log in</a>.</p>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/password_reset_confirm.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <title>Password Reset Confirm</title>
</head>
<body>
    <div class="container">
        <h2>Set New Password</h2>
        <form action="." method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Set Password</button>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/password_reset_done.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <title>Password Reset Done</title>
</head>
<body>
    <div class="container">
        <h2>Password Reset Done</h2>
        <p>An email has been sent with instructions to reset your password.</p>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/password_reset_email.html
Хтось запросив відновлення пароля {{ email }}. Перейдіть за посиланням нижче:
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
Ваш username, у випадку якщо ви забули: {{ user.get_username }}

users/templates/users/profile.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
	<section class="section section--first section--bg" data-bg="{% static "main/img/bg/section__bg.jpg" %}">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="section__wrap">
						<h1 class="section__title section__title--head">My Affordable</h1>
						<ul class="breadcrumbs">
							<li class="breadcrumbs__item"><a href="{% url "main:index" %}">Головна</a></li>
							<li class="breadcrumbs__item breadcrumbs__item--active">Профіль</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
	<div class="content">
		<div class="profile">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<div class="profile__content">
							{% csrf_token %}
							<div class="profile__user">
								<div class="profile__avatar">
									<img src="{% static "main/img/bg/user.svg" %}" alt="">
								</div>
								<div class="profile__meta">
									<h3>{{ user.username }}</h3>
									<span>Affordable ID: {{ user.id }}</span>
								</div>
							</div>
							<ul class="nav nav-tabs content__tabs content__tabs--profile" id="content__tabs" role="tablist">
								<li class="nav-item" role="presentation">
									<button id="1-tab" class="active" data-bs-toggle="tab" data-bs-target="#tab-1" type="button" role="tab" aria-controls="tab-1" aria-selected="true">Профіль</button>
								</li>
								<li class="nav-item" role="presentation">
									<button id="3-tab" data-bs-toggle="tab" data-bs-target="#tab-3" type="button" role="tab" aria-controls="tab-3" aria-selected="false">Налаштування</button>
								</li>
							</ul>
							<form class="profile__logout" action="{% url 'users:logout' %}" method="post">
								{% csrf_token %}
								<button type="submit">
									<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
										<path d="M4,12a1,1,0,0,0,1,1h7.59l-2.3,2.29a1,1,0,0,0,0,1.42,1,1,0,0,0,1.42,0l4-4a1,1,0,0,0,.21-.33,1,1,0,0,0,0-.76,1,1,0,0,0-.21-.33l-4-4a1,1,0,1,0-1.42,1.42L12.59,11H5A1,1,0,0,0,4,12ZM17,2H7A3,3,0,0,0,4,5V8A1,1,0,0,0,6,8V5A1,1,0,0,1,7,4H17a1,1,0,0,1,1,1V19a1,1,0,0,1-1,1H7a1,1,0,0,1-1-1V16a1,1,0,0,0-2,0v3a3,3,0,0,0,3,3H17a3,3,0,0,0,3-3V5A3,3,0,0,0,17,2Z"/>
									</svg>
									<span>Вийти</span>
								</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="tab-content">
				<div class="tab-pane fade show active" id="tab-1" role="tabpanel" aria-labelledby="1-tab" tabindex="0">
					<div class="row">
						<div class="col-12 col-sm-6 col-xl-3">
							<div class="stats">
								<span>Квиток</span>
								<p>{{ user.tickets.price }}</p>
								<img src="{% static "main/img/bg/credit-card.svg" %}" alt="">
							</div>
						</div>
						<div class="col-12 col-sm-6 col-xl-3">
							<div class="stats">
								<span>Переглянуті фільми</span>
								<p>1 172</p>
								<img src="{% static "main/img/bg/film.svg" %}" alt="">
							</div>
						</div>
						<div class="col-12 col-sm-6 col-xl-3">
							<div class="stats">
								<span>Ваші коментарі</span>
								<p>2 573</p>
								<img src="{% static "main/img/bg/comments.svg" %}" alt="">
							</div>
						</div>
						<div class="col-12 col-sm-6 col-xl-3">
							<div class="stats">
								<span>Ваші відгуки</span>
								<p>1 021</p>
								<img src="{% static "main/img/bg/star-half-alt.svg" %}" alt="">
							</div>
						</div>
						<div class="col-12">
							<div class="dashbox">
								<div class="dashbox__title">
									<h3><img src="{% static "main/img/bg/film.svg" %}" alt="">Недавно переглянуті</h3>

									<div class="dashbox__wrap">
										<a class="dashbox__refresh" href="#"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21,11a1,1,0,0,0-1,1,8.05,8.05,0,1,1-2.22-5.5h-2.4a1,1,0,0,0,0,2h4.53a1,1,0,0,0,1-1V3a1,1,0,0,0-2,0V4.77A10,10,0,1,0,22,12,1,1,0,0,0,21,11Z"/></svg></a>
										<a class="dashbox__more" href="{% url "cinema:catalog" %}">Всі</a>
									</div>
								</div>
								<div class="dashbox__table-wrap dashbox__table-wrap--1">
									<table class="dashbox__table">
										<thead>
											<tr>
												<th>ID</th>
												<th>НАЗВА</th>
												<th>КАТЕГОРІЯ</th>
												<th>РЕЙТИНГ</th>
											</tr>
										</thead>
										<tbody>
										{% for seat in booked_seats %}
                                        <tr>
                                            <td>
                                                <div class="dashbox__table-text">{{ seat.id }}</div>
                                            </td>
                                            <td>
                                                <div class="dashbox__table-text"><a href="">{{ seat.movie.title }}</a></div>
                                            </td>
                                            <td>
                                                <div class="dashbox__table-text">{{ seat.seat_number }}</div>
                                            </td>
                                            <td>
                                                <div class="dashbox__table-text dashbox__table-text--rate">{{ seat.movie.price }}</div>
                                            </td>
                                        </tr>
										{% empty %}
										<tr>
											<td>
                                                <div class="dashbox__table-text">Ви ще не забронювали жодного місця.</div>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="tab-pane fade" id="tab-3" role="tabpanel" aria-labelledby="3-tab" tabindex="0">
					<div class="row">
						<div class="col-12 col-lg-6">
							<form action="#" class="sign__form sign__form--profile">
								<div class="row">
									<div class="col-12">
										<h4 class="sign__title">Деталі профілю</h4>
									</div>
									<div class="col-12 col-md-6 col-lg-12 col-xl-6">
										<div class="sign__group">
											<label class="sign__label" for="username">Логін</label>
											<input id="username" type="text" name="username" class="sign__input" placeholder="{{ user.username }}">
										</div>
									</div>
									<div class="col-12 col-md-6 col-lg-12 col-xl-6">
										<div class="sign__group">
											<label class="sign__label" for="email">Пошта</label>
											<input id="email2" type="text" name="email" class="sign__input" placeholder="{{ user.email }}">
										</div>
									</div>
									<div class="col-12 col-md-6 col-lg-12 col-xl-6">
										<div class="sign__group">
											<label class="sign__label" for="firstname">Ім'я</label>
											<input id="firstname" type="text" name="firstname" class="sign__input" placeholder="{{ user.first_name }}">
										</div>
									</div>
									<div class="col-12 col-md-6 col-lg-12 col-xl-6">
										<div class="sign__group">
											<label class="sign__label" for="lastname">Прізвище</label>
											<input id="lastname" type="text" name="lastname" class="sign__input" placeholder="{{ user.last_name}}">
										</div>
									</div>
									<div class="col-12">
										<button class="sign__btn sign__btn--small" type="button"><span>Зберегти</span></button>
									</div>
								</div>
							</form>
						</div>
						<div class="col-12 col-lg-6">
							<form action="#" class="sign__form sign__form--profile">
								<div class="row">
									<div class="col-12">
										<h4 class="sign__title">Змінити пароль</h4>
									</div>
									<div class="col-12 col-md-6 col-lg-12 col-xl-6">
										<div class="sign__group">
											<label class="sign__label" for="oldpass">Старий пароль</label>
											<input id="oldpass" type="password" name="oldpass" class="sign__input">
										</div>
									</div>
									<div class="col-12 col-md-6 col-lg-12 col-xl-6">
										<div class="sign__group">
											<label class="sign__label" for="newpass">Новий пароль</label>
											<input id="newpass" type="password" name="newpass" class="sign__input">
										</div>
									</div>
									<div class="col-12 col-md-6 col-lg-12 col-xl-6">
										<div class="sign__group">
											<label class="sign__label" for="confirmpass">Підтвердіть новий пароль</label>
											<input id="confirmpass" type="password" name="confirmpass" class="sign__input">
										</div>
									</div>
									<div class="col-12">
										<button class="sign__btn sign__btn--small" type="button"><span>Змінити</span></button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

users/templates/users/signin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/splide.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/styles.css' %}">
    <link rel="icon" type="image/png" href="{% static 'icon/favicon-32x32.png' %}" sizes="32x32">
    <link rel="apple-touch-icon" href="{% static 'icon/favicon-32x32.png' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=LXGW+WenKai+TC&family=Rubik:ital,wght@0,300..900;1,300..900&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <title>Affordable - Вхід</title>
</head>
<body>
    <div class="sign section--bg" style="background-image: url('{% static 'main/img/bg/section__bg.jpg' %}');">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="sign__content">
                        <form action="{% url 'users:signin' %}" method="post" class="sign__form">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ next }}">
                            <a href="{% url 'main:index' %}" class="sign__logo">
                                <h2>Affordable</h2>
                            </a>
                            {% if form.non_field_errors %}
                                <div class="alert alert-danger">
                                    {% for error in form.non_field_errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                            <div class="sign__group">
                                <input id="id_username" name="username" type="text" class="sign__input" placeholder="Пошта">
                                {% if form.username.errors %}
                                    <div class="alert alert-danger">
                                        {% for error in form.username.errors %}
                                            <p>{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="sign__group">
                                <input id="id_password" name="password" type="password" class="sign__input" placeholder="Пароль">
                                {% if form.password.errors %}
                                    <div class="alert alert-danger">
                                        {% for error in form.password.errors %}
                                            <p>{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="sign__group sign__group--checkbox">
                                <input id="remember" name="remember" type="checkbox" value="1" checked="checked">
                                <label for="remember">Запам'ятати мене</label>
                            </div>
                            <button class="sign__btn" type="submit"><span>Ввійти</span></button>
                            <span class="sign__text">Немає акаунта? <a href="{% url 'users:signup' %}">Зареєструйтесь!</a></span>
                            <span class="sign__text"><a href="{% url 'users:password_reset' %}">Забули пароль?</a></span>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

users/templates/users/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/splide.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/styles.css' %}">
    <link rel="icon" type="image/png" href="{% static 'icon/favicon-32x32.png' %}" sizes="32x32">
    <link rel="apple-touch-icon" href="{% static 'icon/favicon-32x32.png' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=LXGW+WenKai+TC&family=Rubik:ital,wght@0,300..900;1,300..900&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <title>Affordable - Реєстрація</title>
</head>
<body>
    <div class="sign section--bg" style="background-image: url('{% static 'main/img/bg/section__bg.jpg' %}');">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="sign__content">
                        <form action="{% url 'users:signup' %}" method="post" class="sign__form">
                            {% csrf_token %}
                            <a href="{% url 'main:index' %}" class="sign__logo">
                                <h2>Affordable</h2>
                            </a>
                            {% if form.non_field_errors %}
                                <div class="alert alert-danger">
                                    {% for error in form.non_field_errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                            <div class="sign__group">
                                <input id="id_first_name" name="first_name" type="text" class="sign__input" placeholder="Ім'я">
                                {% if form.first_name.errors %}
                                    <div class="alert alert-danger">
                                        {% for error in form.first_name.errors %}
                                            <p>{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="sign__group">
                                <input id="id_last_name" name="last_name" type="text" class="sign__input" placeholder="Прізвище">
                                {% if form.last_name.errors %}
                                    <div class="alert alert-danger">
                                        {% for error in form.last_name.errors %}
                                            <p>{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="sign__group">
                                <input id="id_username" name="username" type="text" class="sign__input" placeholder="Користувач">
                                {% if form.username.errors %}
                                    <div class="alert alert-danger">
                                        {% for error in form.username.errors %}
                                            <p>{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="sign__group">
                                <input id="id_email" name="email" type="email" class="sign__input" placeholder="Пошта">
                                {% if form.email.errors %}
                                    <div class="alert alert-danger">
                                        {% for error in form.email.errors %}
                                            <p>{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="sign__group">
                                <input id="id_password1" name="password1" type="password" class="sign__input" placeholder="Пароль">
                                {% if form.password1.errors %}
                                    <div class="alert alert-danger">
                                        {% for error in form.password1.errors %}
                                            <p>{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="sign__group">
                                <input id="id_password2" name="password2" type="password" class="sign__input" placeholder="Повторіть пароль">
                                {% if form.password2.errors %}
                                    <div class="alert alert-danger">
                                        {% for error in form.password2.errors %}
                                            <p>{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                            <button class="sign__btn" type="submit"><span>Зареєструватись</span></button>
                            <span class="sign__text">Вже маєте акаунт? <a href="{% url 'users:signin' %}">Увійдіть!</a></span>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>