affordable/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("cinema.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views as main_views

app_name = "main"

urlpatterns = [
    path("", main_views.MovieView.as_view(), name="index"),
    path("about/", main_views.MovieAboutView.as_view(), name="about"),
    path("contacts/", main_views.MovieContactsView.as_view(), name="contacts"),
    path("privacy/", main_views.MoviePrivacyView.as_view(), name="privacy"),
    path("help-center/", main_views.MovieFaqView.as_view(), name="faq"),
]

main/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.conf import settings

class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Назва")
    description = models.TextField(blank=True, null=True, verbose_name="Опис")
    slug = models.SlugField(max_length=200, unique=True, verbose_name="URL")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категорія"
        verbose_name_plural = "Категорії"

class Actor(models.Model):
    name = models.CharField(max_length=200, verbose_name="Ім'я")
    age = models.PositiveSmallIntegerField(default=0, verbose_name="Вік")
    description = models.TextField(blank=True, null=True, verbose_name="Опис")
    image = models.ImageField(upload_to="actors/", verbose_name="Зображення")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Актори і режисери"
        verbose_name_plural = "Актори і режисери"


class Genre(models.Model):
    name = models.CharField(max_length=50, verbose_name="Назва")
    description = models.TextField(blank=True, null=True, verbose_name="Опис")
    slug = models.SlugField(max_length=200, unique=True, verbose_name="URL")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанри"

class Seat(models.Model):
    seat_number = models.PositiveSmallIntegerField(verbose_name="Номер місця")
    start_time = models.DateTimeField(verbose_name="Дата початку показу")
    end_time = models.DateTimeField(verbose_name="Дата закінчення показу")
    status = models.CharField(
        max_length=20,
        choices=[
            ('free', 'Вільне'),
            ('reserved', 'Зарезервоване'),
            ('sold', 'Продане'),
        ],
        default='free',
        verbose_name="Статус місця"
    )

    def __str__(self):
        return f"Місце {self.seat_number} для фільму"

    class Meta:
        verbose_name = "Місце для показу"
        verbose_name_plural = "Місця для показу"

class Movie(models.Model):
    title = models.CharField(max_length=50, verbose_name="Назва фільму", unique=True)
    slug = models.SlugField(max_length=200, unique=True, verbose_name="URL")
    age = models.PositiveSmallIntegerField(verbose_name="Обмеження у віці")
    year = models.DateField(default=timezone.now, verbose_name="Дата виходу")
    video = models.FileField(upload_to="main_video", verbose_name="Трейлер фільму")
    date = models.DateTimeField(default=timezone.now, verbose_name="Початок фільму")
    runtime = models.PositiveSmallIntegerField(default=0, verbose_name="Тривалість фільму", help_text="Тривалість у хвилинах")
    poster = models.ImageField(upload_to="main_img", blank=True, null=True, verbose_name="Постер")
    img = models.ImageField(upload_to="main_img", blank=True, null=True, verbose_name="Прев'ю фільму")
    description = models.TextField(blank=True, null=True, verbose_name="Опис фільму")
    country = models.CharField(max_length=100, verbose_name="Країна")
    movie_rating = models.DecimalField(max_digits=3, decimal_places=1, default=0.0, verbose_name="Рейтинг фільму")
    world_premiere = models.DateField(default=timezone.now, verbose_name="Світова прем'єра")
    budget = models.PositiveIntegerField(default=0, verbose_name="Бюджет", help_text="Вказувати суму в гривнях")
    draft = models.BooleanField(verbose_name="Чорновик", default=False)
    price = models.PositiveIntegerField(default=0, verbose_name="Ціна фільма", help_text="Вказувати ціну в гривнях")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Дата створення замрвлення:")

    seat = models.ManyToManyField(Seat, verbose_name="Час сенасу", blank=True, related_name="film_session")
    directors = models.ManyToManyField(Actor, verbose_name="Режисер", related_name="film_directors")
    actors = models.ManyToManyField(Actor, verbose_name="Актор", related_name="film_actors")
    genres = models.ManyToManyField(Genre, verbose_name="Жанри", related_name="film_genres")
    category = models.ForeignKey(Category, verbose_name="Категорія", on_delete=models.SET_NULL, null=True, related_name="film_category")

    def __str__(self):
        return self.title

    def get_average_rating(self):
        reviews = self.reviews.all()
        if reviews.exists():
            return reviews.aggregate(models.Avg('rating'))['rating__avg']
        return 0.0

    def get_absolute_url(self):
        return reverse("movie_detail", args=[self.slug])

    def display_id(self):
        return f"{self.id:05}"

    class Meta:
        verbose_name = "Фільм"
        verbose_name_plural = "Фільми"

class PaymentIntent(models.Model):
    referrer = models.URLField(verbose_name="Посилання")
    movie_title = models.CharField(max_length=250, verbose_name="Заголовок фільму")
    seat_number = models.CharField(max_length=50, verbose_name="Номер місця")

    class Meta:
        verbose_name = "Причина платежу"
        verbose_name_plural = "Причини платежів"

class Payment(models.Model):
    first_name = models.CharField(max_length=250, verbose_name="Ім'я користувача")
    last_name = models.CharField(max_length=250, verbose_name="Прізвище користувача")
    email = models.EmailField(max_length=250, verbose_name="Пошта користувача")
    phone = models.CharField(max_length=250, verbose_name="Номер теелфону користувача")
    movie = models.ForeignKey(Movie, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Фільм")
    seat_number = models.PositiveSmallIntegerField(default=0, verbose_name="Номер місця")

    class Meta:
        verbose_name = "Платіж"
        verbose_name_plural = "Платежі"

class MovieShots(models.Model):
    title = models.CharField(verbose_name="Заголовок", max_length=100)
    description = models.TextField(verbose_name="Опис")
    image = models.ImageField(verbose_name="Зображення", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фільм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр з фільма"
        verbose_name_plural = "Кадри з фільму"

class Rating(models.Model):
    ip = models.CharField(max_length=15, verbose_name="IP-адреса")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="Фільм", related_name="ratings")

    def __str__(self):
        return f"{self.ip} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Comments(models.Model):
    name = models.CharField(max_length=100, verbose_name="Ім'я")
    text = models.TextField(max_length=5000, verbose_name="Повідомлення")
    parent = models.ForeignKey('self', verbose_name="Батько", on_delete=models.CASCADE, blank=True, null=True, related_name='replies')
    movie = models.ForeignKey(Movie, verbose_name="Фільм", on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Дата створення")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    likes = models.PositiveIntegerField(verbose_name="Лайки", default=0)
    dislikes = models.PositiveIntegerField(verbose_name="Дизлайки", default=0)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Коментар"
        verbose_name_plural = "Коментарі"


class Reviews(models.Model):
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    text = models.TextField(max_length=5000, verbose_name="Повідомлення")
    movie = models.ForeignKey(Movie, verbose_name="Фільм", on_delete=models.CASCADE, related_name='reviews')
    rating = models.PositiveSmallIntegerField(verbose_name="Рейтинг")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Дата створення")

    def __str__(self):
        return f"{self.title} - {self.movie}"

    class Meta:
        verbose_name = "Відгук"
        verbose_name_plural = "Відгуки"

main/views.py
from django.views.generic.list import ListView
from django.views.generic.base import View
from django.shortcuts import render
from main.models import Movie

class MovieView(ListView):
    model = Movie
    queryset = Movie.objects.all()
    template_name = "main/index.html"
    context_object_name = "movies"

class MovieAboutView(View):
    def get(self, request):
        return render(request, "main/about.html")

class MoviePrivacyView(View):
    def get(self, request):
        return render(request, "main/privacy.html")

class MovieContactsView(View):
    def get(self, request):
        return render(request, "main/contacts.html")
    
class MovieFaqView(View):
    def get(self, request):
        return render(request, "main/faq.html")

main/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
	<section class="section section--first section--bg" data-bg="{% static "main/img/bg/section__bg.jpg" %}">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="section__wrap">
						<h1 class="section__title section__title--head">Про нас</h1>
						<ul class="breadcrumbs">
							<li class="breadcrumbs__item"><a href="{% url "main:index" %}">Головна</a></li>
							<li class="breadcrumbs__item breadcrumbs__item--active">Про нас</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="section">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h2 class="section__title"><b>Affordable</b> – Найкраще місце для фільмів</h2>

					<p class="section__text">Ласкаво просимо до кінотеатру <b>Affordable</b>, ідеальне місце для всіх любителів кіно. Пориньте у світ захоплюючих історій, приголомшливих візуальних ефектів і незабутніх виступів. Ознайомтеся з нашою великою бібліотекою фільмів, що охоплюють різні жанри, епохи та культури.</p>

					<p class="section__text">Насолоджуйтесь радістю кіно з нашими підібраними колекціями, що містять підібрані фільми, згруповані за темами, режисерами чи акторами. Пориньте у світ кінематографічної магії та дозвольте собі перенестися в нові сфери уяви та емоцій.</p>
				</div>
				<div class="col-12 col-md-6 col-lg-4">
					<div class="feature">
						<span class="feature__icon">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19,2H5A3,3,0,0,0,2,5V15a3,3,0,0,0,3,3H7.64l-.58,1a2,2,0,0,0,0,2,2,2,0,0,0,1.75,1h6.46A2,2,0,0,0,17,21a2,2,0,0,0,0-2l-.59-1H19a3,3,0,0,0,3-3V5A3,3,0,0,0,19,2ZM8.77,20,10,18H14l1.2,2ZM20,15a1,1,0,0,1-1,1H5a1,1,0,0,1-1-1V14H20Zm0-3H4V5A1,1,0,0,1,5,4H19a1,1,0,0,1,1,1Z"/></svg>
						</span>
						<h3 class="feature__title">Найвища якість</h3>
						<p class="feature__text">Насолоджуйтесь переглядом фільмів, як ніколи раніше, завдяки 3D показу. Пориньте в приголомшливі візуальні ефекти, яскраві кольори та кришталево чисті деталі.</p>
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-4">
					<div class="feature">
						<span class="feature__icon">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21,2a1,1,0,0,0-1,1V5H18V3a1,1,0,0,0-2,0V4H8V3A1,1,0,0,0,6,3V5H4V3A1,1,0,0,0,2,3V21a1,1,0,0,0,2,0V19H6v2a1,1,0,0,0,2,0V20h8v1a1,1,0,0,0,2,0V19h2v2a1,1,0,0,0,2,0V3A1,1,0,0,0,21,2ZM6,17H4V15H6Zm0-4H4V11H6ZM6,9H4V7H6Zm10,9H8V13h8Zm0-7H8V6h8Zm4,6H18V15h2Zm0-4H18V11h2Zm0-4H18V7h2Z"/></svg>
						</span>
						<h3 class="feature__title">Велике розмаїття фільмів</h3>
						<p class="feature__text">Відкрийте для себе величезну та різноманітну колекцію фільмів у нашій великій базі даних. З тисячами назв на вибір, у вас ніколи не закінчаться варіанти.</p>
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-4">
					<div class="feature">
						<span class="feature__icon">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M18,6H14.41l2.3-2.29a1,1,0,1,0-1.42-1.42L12,5.54l-1.17-2a1,1,0,1,0-1.74,1L10,6H6A3,3,0,0,0,3,9v8a3,3,0,0,0,3,3v1a1,1,0,0,0,2,0V20h8v1a1,1,0,0,0,2,0V20a3,3,0,0,0,3-3V9A3,3,0,0,0,18,6Zm1,11a1,1,0,0,1-1,1H6a1,1,0,0,1-1-1V9A1,1,0,0,1,6,8H18a1,1,0,0,1,1,1Z"></path></svg>
						</span>
						<h3 class="feature__title">Доступність</h3>
						<p class="feature__text">Наш кінотеатр обладнаний для легкого доступу для людей з обмеженими можливостями, включаючи пандуси та спеціальні зони.</p>
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-4">
					<div class="feature">
						<span class="feature__icon">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M9,10a1,1,0,0,0-1,1v2a1,1,0,0,0,2,0V11A1,1,0,0,0,9,10Zm12,1a1,1,0,0,0,1-1V6a1,1,0,0,0-1-1H3A1,1,0,0,0,2,6v4a1,1,0,0,0,1,1,1,1,0,0,1,0,2,1,1,0,0,0-1,1v4a1,1,0,0,0,1,1H21a1,1,0,0,0,1-1V14a1,1,0,0,0-1-1,1,1,0,0,1,0-2ZM20,9.18a3,3,0,0,0,0,5.64V17H10a1,1,0,0,0-2,0H4V14.82A3,3,0,0,0,4,9.18V7H8a1,1,0,0,0,2,0H20Z"></path></svg>
						</span>
						<h3 class="feature__title">Ранній доступ до нових фільмів</h3>
						<p class="feature__text">Дізнавайтеся найновіші фільми та ексклюзивний контент першими завдяки нашій функції раннього доступу. Зазирніть у майбутні релізи, отримайте доступ до спеціальних показів і будьте на крок попереду.</p>
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-4">
					<div class="feature">
						<span class="feature__icon">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12.83,13.45a1,1,0,0,0-1.66,0l-4,6a1,1,0,0,0,0,1A1,1,0,0,0,8,21h8a1,1,0,0,0,.88-.53,1,1,0,0,0-.05-1ZM9.87,19,12,15.8,14.13,19ZM19,3H5A3,3,0,0,0,2,6v9a3,3,0,0,0,3,3h.85a1,1,0,1,0,0-2H5a1,1,0,0,1-1-1V6A1,1,0,0,1,5,5H19a1,1,0,0,1,1,1v9a1,1,0,0,1-1,1h-.85a1,1,0,0,0,0,2H19a3,3,0,0,0,3-3V6A3,3,0,0,0,19,3Z"></path></svg>
						</span>
						<h3 class="feature__title">Комфортні умови перегляду</h3>
						<p class="feature__text">Наші зручні сидіння та сучасне обладнання забезпечують комфортне і незабутнє переглядання фільмів для всіх наших глядачів.</p>
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-4">
					<div class="feature">
						<span class="feature__icon">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.05566,12h-2a1,1,0,0,0,0,2v2H17.8714a2.96481,2.96481,0,0,0,.18426-1A2.99955,2.99955,0,0,0,12.458,13.50049a.99992.99992,0,1,0,1.73242.999A1.0009,1.0009,0,0,1,15.05566,14a1,1,0,0,1,0,2,1,1,0,0,0,0,2,1,1,0,1,1,0,2,1.0009,1.0009,0,0,1-.86523-.49951.99992.99992,0,1,0-1.73242.999A2.99955,2.99955,0,0,0,18.05566,19a2.96481,2.96481,0,0,0-.18426-1h1.18426v3a1,1,0,0,0,2,0V14a1,1,0,1,0,0-2ZM9.08594,11.24268a.99963.99963,0,1,0,1.93945-.48536L9.26855,3.72754a2.28044,2.28044,0,0,0-4.4248,0L3.08594,10.75732a.99963.99963,0,1,0,1.93945.48536L5.58618,9H8.52545ZM6.0863,7l.6969-2.78711a.29222.29222,0,0,1,.5459,0L8.02563,7Zm7.96936,0h1a1.001,1.001,0,0,1,1,1V9a1,1,0,0,0,2,0V8a3.00328,3.00328,0,0,0-3-3h-1a1,1,0,0,0,0,2Zm-4,9h-1a1.001,1.001,0,0,1-1-1V14a1,1,0,0,0-2,0v1a3.00328,3.00328,0,0,0,3,3h1a1,1,0,0,0,0-2Z"></path></svg>
						</span>
						<h3 class="feature__title">Субтитри для поганочуючих</h3>
						<p class="feature__text">Ми пропонуємо субтитри для всіх фільмів. Це дозволяє нашим глядачам з вадами слуху насолоджуватися кіно, маючи доступ до текстового відтворення аудіосупроводу.</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="section section--dark">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h2 class="section__title">Як це працює</h2>
				</div>
				<div class="col-12 col-lg-4">
					<div class="how">
						<span class="how__number">01</span>
						<h3 class="how__title">Створіть акаунт</h3>
						<p class="how__text">Почніть свій шлях перегляду фільмів, створивши персоналізований обліковий запис на нашій платформі. Легко зареєструйтеся та отримайте доступ до світу розваг.</p>
					</div>
				</div>
				<div class="col-12 col-lg-4">
					<div class="how">
						<span class="how__number">02</span>
						<h3 class="how__title">Купіть квиток</h3>
						<p class="how__text">Виберіть ідеальне місце в кінотеатрі, яке відповідає вашим уподобанням. Ми пропонуємо широкий вибір місць від базових до преміум.</p>
					</div>
				</div>
				<div class="col-12 col-lg-4">
					<div class="how">
						<span class="how__number">03</span>
						<h3 class="how__title">Насолоджуйтесь Affordable</h3>
						<p class="how__text">Пориньте у світ Affordable, де на вас чекає необмежена кількість фільмів. З нашою величезною колекцією фільмів кожен знайде щось для себе.</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="section section--dark section--bt">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h2 class="section__title section__title--carousel">Дорожня карта</h2>
				</div>
				<div class="col-12">
					<div class="section__roadmap splide splide--roadmap">
						<div class="splide__arrows">
							<button class="splide__arrow splide__arrow--prev" type="button"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M17,11H9.41l3.3-3.29a1,1,0,1,0-1.42-1.42l-5,5a1,1,0,0,0-.21.33,1,1,0,0,0,0,.76,1,1,0,0,0,.21.33l5,5a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42L9.41,13H17a1,1,0,0,0,0-2Z"/></svg></button>
							<button class="splide__arrow splide__arrow--next" type="button"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M17.92,11.62a1,1,0,0,0-.21-.33l-5-5a1,1,0,0,0-1.42,1.42L14.59,11H7a1,1,0,0,0,0,2h7.59l-3.3,3.29a1,1,0,0,0,0,1.42,1,1,0,0,0,1.42,0l5-5a1,1,0,0,0,.21-.33A1,1,0,0,0,17.92,11.62Z"/></svg></button>
						</div>
						<div class="splide__track">
							<ul class="splide__list">
								<li class="splide__slide">
									<div class="roadmap roadmap--active">
										<h3 class="roadmap__title">2024 M1</h3>
										<ul class="roadmap__list">
											<li>Провели маркетингові дослідження фільмів, вивчили потреби і переваги цільової аудиторії.</li>
											<li>Визначили основні цілі та завдання сайту: надання контенту, функціонал та дизайн.</li>
										</ul>
									</div>
								</li>
								<li class="splide__slide">
									<div class="roadmap roadmap--active">
										<h3 class="roadmap__title">2024 M2</h3>
										<ul class="roadmap__list">
											<li>Створили інформаційну архітектуру сайту, визначивши основні розділи та категорії контенту.</li>
											<li>Розробили привабливий та інтуїтивно зрозумілий дизайну сайту, що забезпечує зручну навігацію та високу інтерактивність користувачів.</li>
										</ul>
									</div>
								</li>
								<li class="splide__slide">
									<div class="roadmap">
										<h3 class="roadmap__title">2024 M3</h3>
										<ul class="roadmap__list">
											<li>Створили бази даних фільмів та мультфільмів, включаючи інформацію про назву, жанр, акторів, рейтинги та відгуки.</li>
											<li>Розробили потужну пошукову систему, яка дозволить користувачам легко знаходити фільми, мультфільми та аніме.</li>
										</ul>
									</div>
								</li>
								<li class="splide__slide">
									<div class="roadmap">
										<h3 class="roadmap__title">2024 M4</h3>
										<ul class="roadmap__list">
											<li>Розробили систему реєстрації та авторизації користувачів для створення особистих кабінетів.</li>
											<li>Реалізація можливості залишати відгуки та оцінки.</li>
										</ul>
									</div>
								</li>
								<li class="splide__slide">
									<div class="roadmap">
										<h3 class="roadmap__title">2024 M5</h3>
										<ul class="roadmap__list">
											<li>Захист даних користувачів, застосування відповідних протоколів безпеки.</li>
											<li>Тестування сайту на різних пристроях та браузерах, виправлення помилок та покращення продуктивності.</li>
										</ul>
									</div>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock content %}

main/templates/main/privacy.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
	<section class="section section--first section--bg" data-bg="{% static "main/img/bg/section__bg.jpg" %}">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="section__wrap">
						<h1 class="section__title section__title--head">Політика конфіденційності</h1>
						<ul class="breadcrumbs">
							<li class="breadcrumbs__item"><a href="{% url "main:index" %}">Головна</a></li>
							<li class="breadcrumbs__item breadcrumbs__item--active">Політика конфіденційності</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="section">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<p class="section__text">Дякуємо за відвідування веб-сайту кінотеатру "Affordable". Ми дуже цінуємо вашу присутність тут і зобов'язуємося забезпечувати вам максимальний рівень конфіденційності та захисту ваших персональних даних. Наша політика конфіденційності пояснює, як ми збираємо, використовуємо, захищаємо та розкриваємо вашу інформацію в контексті відвідування нашого веб-сайту та взаємодії з ним.</p>
					<div class="section__list">
						<ol>
							<li>
								<h4>Збір та використання інформації:</h4>
								<ol>
									<li>Ми збираємо різноманітну інформацію, включаючи, але не обмежуючись, ім'я, адресу електронної пошти, контактні дані, інформацію про пристрій, IP-адресу та іншу інформацію, яку ви нам надаєте чи яку ми можемо отримувати під час використання веб-сайту.</li>
									<li>Ми використовуємо цю інформацію для забезпечення вам доступу до послуг кінотеатру, відправлення новин та акційних пропозицій, а також для покращення якості наших послуг.	</li>
								</ol>
							</li>
							<li>
								<h4>Захист інформації:</h4>
								<ol>
									<li>Ми приділяємо велику увагу захисту вашої інформації та вживаємо відповідних заходів безпеки для захисту її від несанкціонованого доступу, втрати, використання чи розголошення.</li>
								</ol>
							</li>
							<li>
								<h4>Розкриття інформації третім сторонам:</h4>
								<ol>
									<li>Ми не розкриваємо вашу персональну інформацію третім сторонам без вашої згоди, за винятком випадків, передбачених законом або необхідних для надання послуг, що надаються вами.</li>
								</ol>
							</li>
							<li>
								<h4>Користувацькі права:</h4>
								<ol>
									<li>Ви маєте право змінювати, видаляти чи оновлювати свою персональну інформацію, а також вибирати, як ми використовуємо ваші дані. </li>
									<li>Ви також можете в будь-який момент відмовитися від отримання рекламних повідомлень від нас.</li>
								</ol>
							</li>
							<li>
								<h4>Політика щодо дітей:</h4>
								<ol>
									<li>Наш веб-сайт не призначений для використання особами, які не досягли 18 років. Ми не збираємо свідомо інформацію від дітей молодших 18 років.</li>
									<li>Якщо ми виявимо, що ми зібрали інформацію від дитини без згоди батьків, ми негайно видалимо цю інформацію з наших серверів.</li>
								</ol>
							</li>
							<li>
								<h4>Зміни у політиці конфіденційності:</h4>
								<ol>
									<li>Ми можемо час від часу оновлювати цю політику конфіденційності. Будь ласка, періодично переглядайте цю сторінку, щоб бути в курсі будь-яких змін. </li>
									<li>Ваше продовження використання веб-сайту після опублікування змін у цій політиці буде вважатися вашою згодою з такими змінами.</li>
								</ol>
							</li>
						</ol>
					</div>
					<p class="section__text">Ця політика конфіденційності вступає в дію з моменту її публікації та стосується всіх відвідувачів нашого веб-сайту.</p>
					<p class="section__text">Якщо у вас є будь-які питання щодо нашої політики конфіденційності, будь ласка, <a href="{% url "main:contacts" %}">зв'яжіться з нами</a></p>
				</div>
			</div>
		</div>
	</section>
{% endblock content %}